server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: password
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  ai:
    ollama:
      base-url: http://localhost:11434


mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.xk.entity
  mapper-locations: classpath:mapper/*.xml

flyway:
  enabled: true
  baseline-on-migrate: true
  locations: classpath:db/migration

file:
  upload:
    path: ""

jwt:
  secret: ""